sudo: false

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

scala:
   - 2.11.8

jdk:
  - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION coverage test it:test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
